### ISSUE TITLE
Add Basic health check tests

### ISSUE THREAD

**Issue by KletskovG** [KletskovG/kletskovg.tech#20]
**Add tests for frontend and backend while merging to master**

- [x] Add navigation test for frontend (#30)
- [x] Add tests for backend (#31)
- [ ] Add github workflow for merging to master and testing (#32)
